// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaEscolar.API.Data;

#nullable disable

namespace SistemaEscolar.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251127162705_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaEscolar.API.Models.Alumno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EscuelaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("MadreId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PadreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EscuelaId");

                    b.HasIndex("MadreId");

                    b.HasIndex("PadreId");

                    b.ToTable("Alumnos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "García Rodríguez",
                            EscuelaId = 1,
                            FechaNacimiento = new DateTime(2015, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grado = "3° Primaria",
                            MadreId = 2,
                            Nombre = "Carlos",
                            PadreId = 1
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "López Martínez",
                            EscuelaId = 1,
                            FechaNacimiento = new DateTime(2016, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Grado = "2° Primaria",
                            MadreId = 4,
                            Nombre = "Laura",
                            PadreId = 3
                        });
                });

            modelBuilder.Entity("SistemaEscolar.API.Models.Escuela", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Escuelas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Av. Principal 123",
                            Nombre = "Escuela Primaria Benito Juárez",
                            Telefono = "4491234567"
                        },
                        new
                        {
                            Id = 2,
                            Direccion = "Calle Reforma 456",
                            Nombre = "Instituto Miguel Hidalgo",
                            Telefono = "4499876543"
                        });
                });

            modelBuilder.Entity("SistemaEscolar.API.Models.Padre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("EsPadre")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("EsPadre");

                    b.ToTable("Padres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "García",
                            Email = "juan.garcia@email.com",
                            EsPadre = true,
                            Nombre = "Juan",
                            Telefono = "4491111111"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "López",
                            Email = "pedro.lopez@email.com",
                            EsPadre = true,
                            Nombre = "Pedro",
                            Telefono = "4493333333"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Rodríguez",
                            Email = "maria.rodriguez@email.com",
                            EsPadre = false,
                            Nombre = "María",
                            Telefono = "4492222222"
                        },
                        new
                        {
                            Id = 4,
                            Apellido = "Martínez",
                            Email = "ana.martinez@email.com",
                            EsPadre = false,
                            Nombre = "Ana",
                            Telefono = "4494444444"
                        });
                });

            modelBuilder.Entity("SistemaEscolar.API.Models.Alumno", b =>
                {
                    b.HasOne("SistemaEscolar.API.Models.Escuela", "Escuela")
                        .WithMany("Alumnos")
                        .HasForeignKey("EscuelaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaEscolar.API.Models.Padre", "Madre")
                        .WithMany()
                        .HasForeignKey("MadreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaEscolar.API.Models.Padre", "Padre")
                        .WithMany()
                        .HasForeignKey("PadreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Escuela");

                    b.Navigation("Madre");

                    b.Navigation("Padre");
                });

            modelBuilder.Entity("SistemaEscolar.API.Models.Escuela", b =>
                {
                    b.Navigation("Alumnos");
                });
#pragma warning restore 612, 618
        }
    }
}
